---
title: "Exploratory Analysis"
output: html_document
---

##  Gun violence incidents analysis in the United States



### Authors
Team members:
Lufei Chen (lufeic@uw.edu)
Hongye Lin (hlin9@uw.edu)
Shipei Huang (shipeh@uw.edu)
Wendy Bu (wsb22@uw.edu)

### Date

8/4/23 Spring23

### Abstract

Our main question is to analyze the geographic patterns and temporal trends of gun violence incidents in the United States. This question is important because it allows people to identify high-risk areas and to find potential ways to prevent gun violence. To address the question, we will conduct a comprehensive analysis of the dataset obtained from Kaggle, examining changes in the frequency of gun violence incidents over time and exploring potential patterns or correlations with demographic factors.

### Keywords

1. Gun Violence 
2. Public Safety 
3. Social Impact 

### Introduction  

Gun violence is a serious problem that affects residents in the United States. Our project aims to analyze the geographic patterns of gun violence and the reasons behind gun violence in the United States by using the dataset we found from Kaggle. The dataset includes date, location, number of people that were killed, and number of people that were injured of each gun violence incident that were documented from 2013 to 2022.

The research questions that we'll be focusing on are:

1. How has the number of gun violence incidents changed over time in different states and cities? 
2. Are there any seasonal or temporal patterns in gun violence incidents? 
3. Does gun violence differ in cities, suburbs, and rural areas? 
4. Does demographic factors such as age, gender, and ethnicity intersect with gun violence trends? 

The motivation behind our research questions is driven by an urgent need to combat gun violence in the United States. We want to figure out if there’s any certain trends of gun violence by either location, group of people, seasons of the year, etc. By analyzing these questions, we can better understand gun violence and the potential reasons behind it. Since it affects the safety and well-being of all residents in the United States, studying the trends over time and across different areas can help us to learn more about the factors that contribute to gun violence and find ways to prevent it.

### Related Work  

Our topic is investigating the gun violence happened in past several years around the United States. Firstly, We analyze from the locations and draw a map to show which area is affected by gun violence most and least. Secondly, we analyze from the time, we will compare the data through the timeline to find out the rising and falling rate of gun crimes in some areas. Thirdly, we analyze the number of injuried people and death to speculate the type of un-supervised gun around that area. Besides these, we will keep doing more researchs based on the dataset and get more meaningful results. Finally, The result of analysis can be used by the federal governments to enhance security work or used by local government to improve citizens' safety. Why we are doing this analysis? We want to make this land under our feet to become a safer and more trust-worthy environment for anyone who lives than any moment before.

Related Work (links): 

1. "GUN VIOLENCE IN AMERICA AN ANALYSIS OF 2018 CDC DATA". The Educational Fund to Stop Gun Violence. https://efsgv.org/wp-content/uploads/Gun-Violence-in-America_An-Analysis-of-2018-CDC-Data_February-2020.pdf, February 2020. 

2. "What the data says about gun deaths in the U.S." JOHN GRAMLICH. https://www.pewresearch.org/short-reads/2023/04/26/what-the-data-says-about-gun-deaths-in-the-u-s/, APRIL 26, 2023. 

3. "GUN VIOLENCE PROBLEM ANALYSIS SUMMARY REPORT Washington, D.C." National Institute forCriminal Justice Reform. https://cjcc.dc.gov/sites/default/files/dc/sites/cjcc/release_content/attachments/DC%20Gun%20Violence%20Problem%20Analysis%20Summary%20Report.pd, December 2021. 


### The Dataset

1.We found the data set from Kaggle: https://www.kaggle.com/datasets/emmanuelfwerr/gun-violence-incidents-in-the-usa. 

  (This is the source of the data set: https://www.gunviolencearchive.org)  


2. Who collected the data?  
The data was collected from the Gun Violence Archive (GVA).

3. How was the data collected or generated?  
GVA collects data from most law enforcement, government, and commercial sources on a daily basis to provide people with real-time data. Kaggle users then selected data from the GVA website for analysis.

4. Why was the data collected?  

5. How many observations (rows) are in your data? 

6. How many features (columns) are in the data?  

7. What, if any, ethical questions or questions of power do you need to consider when working with this data?  

8. What are possible limitations or problems with this data?   (at least 200 words)

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

scatterplot: recent 10 years (2013-2022) total cases trend

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

map?

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
